name: Portfolio Static Deploy

jobs:
  build:
    # sequence with names of all modules used for building
    use: 
      - tree-install
      - run-commands
    tree-install: 
      use: npm
      env: production
      dirs: 
        - /
    run-commands:
      - npx webpack
      - echo "hello world"
  test:
    run_test: false
  deploy:
    use: s3
    s3:
      bucket: s3_bucket
      access_key: insert_access_key 
      secret_key: insert_secret_key
    build_output_folder: dist

